export const SYNC_USER_DATA = 'SYNC_USER_DATA';

export const VALID_TOKEN_REQUEST = 'VALID_TOKEN_REQUEST';
export const VALID_TOKEN_RECEIVED = 'VALID_TOKEN_RECEIVED';
export const VALID_TOKEN_ERROR = 'VALID_TOKEN_ERROR';