export const SAVE_ARTICLE_REQUEST = 'SAVE_ARTICLE_REQUEST';
export const SAVE_ARTICLE_RECEIVED = 'SAVE_ARTICLE_RECEIVED';
export const SAVE_ARTICLE_ERROR = 'SAVE_ARTICLE_ERROR';

export const QUERY_ARTICLE_BYNUM_REQUEST = 'QUERY_ARTICLE_BYNUM_REQUEST';
export const QUERY_ARTICLE_BYNUM_RECEIVED = 'QUERY_ARTICLE_BYNUM_RECEIVED';
export const QUERY_ARTICLE_BYNUM_ERROR = 'QUERY_ARTICLE_BYNUM_ERROR';

export const QUERY_ALL_ARTICLE_REQUEST = 'QUERY_ALL_ARTICLE_REQUEST';
export const QUERY_ALL_ARTICLE_RECEIVED = 'QUERY_ALL_ARTICLE_RECEIVED';
export const QUERY_ALL_ARTICLE_FAILED = 'QUERY_ALL_ARTICLE_FAILED';
export const QUERY_ALL_ARTICLE_ERROR= 'QUERY_ALL_ARTICLE_ERROR';
